from __future__ import annotations

from typing import Any, Protocol

from tuoming_agent.models import ArtifactRecord, MessageRecord, WorkspaceRecord


class Repository(Protocol):
    def initialize(self) -> None: ...

    def ensure_tenant(self, tenant_id: str, name: str | None = None) -> None: ...

    def create_workspace(self, tenant_id: str, name: str) -> WorkspaceRecord: ...

    def get_workspace(self, tenant_id: str, workspace_id: str) -> WorkspaceRecord: ...

    def list_workspaces(self, tenant_id: str) -> list[WorkspaceRecord]: ...

    def find_mapping_by_fingerprint(
        self, tenant_id: str, domain: str, key_version: int, fingerprint: str
    ) -> dict[str, Any] | None: ...

    def find_mapping_by_token(self, tenant_id: str, token: str) -> dict[str, Any] | None: ...

    def insert_mapping(self, mapping: dict[str, Any]) -> None: ...

    def list_mappings(self, tenant_id: str) -> list[dict[str, Any]]: ...

    def get_artifact(self, tenant_id: str, artifact_id: str) -> ArtifactRecord: ...

    def list_artifacts(self, tenant_id: str, workspace_id: str) -> list[ArtifactRecord]: ...

    def list_messages(self, tenant_id: str, conversation_id: str) -> list[MessageRecord]: ...

